const players = [
    {
        name: "Juan Perez",
        email: "juan.perez@gmail.com",
        nickname: "1234",
        password: "JoanPerer",
        birthdate: "1997-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Miranda Diaz",
        email: "Mirinda@gmail.com",
        nickname: "245",
        password: "Mirinda",
        birthdate: "1997-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Marisol Juarez",
        email: "marijua@gmail.com",
        nickname: "65412",
        password: "Marisu",
        birthdate: "1997-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Laura Escamilla",
        email: "lauE@gmail.com",
        nickname: "564321",
        password: "Laure",
        birthdate: "1999-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Mitzi Gonzalez",
        email: "mitzer@gmail.com",
        nickname: "54648",
        password: "Mitzer",
        birthdate: "1998-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Paola Berenice",
        email: "paopao@gmail.com",
        nickname: "654646",
        password: "Paopao",
        birthdate: "1998-08-02",
        portrait_img: "default.img",
    },
    {
        name: "Areida Jimenez",
        email: "areji@gmail.com",
        nickname: "23123164",
        password: "AreidaJo",
        birthdate: "1995-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Diana Aoiki",
        email: "aokiDiana@gmail.com",
        nickname: "1654654",
        password: "Daina",
        birthdate: "1998-01-02",
        portrait_img: "default.img",
    },
    {
        name: "Aranza Gomez",
        email: "aranGo@gmail.com",
        nickname: "246546",
        password: "AranGo",
        birthdate: "1996-05-02",
        portrait_img: "default.img",
    },
    {
        name: "Maricruz Lopez",
        email: "marilo@gmail.com",
        nickname: "635462",
        password: "Maricru",
        birthdate: "1998-05-02",
        portrait_img: "default.img",
    },
]

export default players